# Generated by Django 5.0.6 on 2024-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
