# Generated by Django 5.0.6 on 2024-06-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_facts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facts',
            name='number',
        ),
        migrations.AddField(
            model_name='facts',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facts',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='facts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
