# Generated by Django 5.0.6 on 2024-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_facts_number_facts_count_facts_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facts',
            name='emoji',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
