# Generated by Django 5.0.6 on 2024-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_facts_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('list_1', models.CharField(max_length=50)),
                ('list_2', models.CharField(max_length=50)),
                ('list_3', models.CharField(max_length=50)),
            ],
        ),
    ]
