# Generated by Django 5.0.6 on 2024-06-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_summery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('detail_title', models.CharField(max_length=200)),
                ('detail_1', models.TextField(blank=True)),
                ('detail_2', models.TextField(blank=True)),
                ('detail_3', models.TextField(blank=True)),
                ('detail_4', models.TextField(blank=True)),
            ],
        ),
    ]
