# Generated by Django 5.0.6 on 2024-06-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('category', models.CharField(choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], max_length=10)),
                ('lightbox_link', models.URLField(blank=True)),
                ('details_link', models.URLField(blank=True)),
            ],
        ),
    ]
