# Generated by Django 5.0.6 on 2024-06-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_url',
            field=models.CharField(max_length=50),
        ),
    ]
